site_name: niaodtiantang
nav:
- 首页: README.md
- 博客: 
    - 首页: blog/README.md
    - 年:
        - 2022: blog/year2022.md
theme: 
   name: material
   custom_dir: docs/overrides
   language: zh
   # logo: 
   # favicon: 
   icon:
        repo: fontawesome/brands/github
   features:
        - navigation.instant
        - navigation.tracking
        - navigation.tabs
        - navigation.tabs.sticky
        - navigation.expand
        - toc.follow
        - navigation.top
        - content.code.annotate
        - announce.dismiss
        - navigation.indexes
        - navigation.expand
        - search.suggest
        - search.highlight
        - search.share
site_description: 让世界更美好
site_url: http://www.niaodtiantang.com/
site_author: Niaodtiantang
copyright: ©2021-2023 Niaodtiantang
plugins:
    - search:
        lang:
            - en
            - ja
            - zh
        separator: '[\s\-\.]+'
    - git-revision-date-localized:
        enable_creation_date: true
        type: iso_datetime
    - glightbox
extra:
  consent:
    title: Cookie consent
    description: >- 
      We use cookies to recognize your repeated visits and preferences, as well
      as to measure the effectiveness of our documentation and whether users
      find what they're searching for. With your consent, you're helping us to
      make our documentation better.
    homepage: https://www.niaodtiantang.com/
    palette: 
 
        # Palette toggle for light mode
        - scheme: default
          toggle:
            icon: material/brightness-7 
            name: Switch to dark mode
 
        # Palette toggle for dark mode
        - scheme: slate
          toggle:
            icon: material/brightness-4
            name: Switch to light mode
repo_url: https://github.com/niaodtiantang/niaodtiantang.github.io/
repo_name: niaodtiantang/niaodtiantang.github.io
edit_uri: https://github.com/niaodtiantang/niaodtiantang.github.io/edit/main/docs/

markdown_extensions:
    - pymdownx.highlight:
        anchor_linenums: true
    - pymdownx.inlinehilite
    - pymdownx.snippets
    - pymdownx.superfences
    - tables
    - footnotes
    - pymdownx.critic
    - pymdownx.caret
    - pymdownx.keys
    - pymdownx.mark
    - pymdownx.tilde
    - attr_list
    - md_in_html
    - admonition
    - pymdownx.details
    - pymdownx.superfences
    - attr_list
    - pymdownx.emoji:
        emoji_index: !!python/name:materialx.emoji.twemoji
        emoji_generator: !!python/name:materialx.emoji.to_svg
