#
site_name: niaodtiantang
nav:
- 首页: README.md
- 博客:
    - blog/index.md
use_directory_urls: false
theme: 
   name: material
   custom_dir: docs/overrides
   language: zh
   # logo: 
   # favicon: 
   icon:
        repo: fontawesome/brands/github
   features:
     - navigation.footer
     - navigation.instant
     - navigation.instant.progress
     - navigation.tracking
     - navigation.tabs
     - navigation.tabs.sticky
     - navigation.expand
     - toc.follow
     - toc.integrate
     - navigation.top
     - content.code.annotate
     - announce.dismiss
     - navigation.indexes
     - navigation.expand
     - search.suggest
     - search.highlight
     - search.share
     - navigation.sections
     - navigation.prune
site_description: 让世界更美好
site_url: https://ndtt.eu.org/
site_author: Niaodtiantang
copyright: ©2021-2024 Niaodtiantang
plugins:
    - search:
        lang:
            - en
            - ja
            - zh
        separator: '[\s\-\.]+'
    - git-revision-date-localized:
        enable_creation_date: true
        type: timeago
        locale: zh
    - glightbox
    - blog
    - rss:
        enabled: !ENV [ CI, false ]
        match_path: blog/posts/.*
        date_from_meta:
          as_creation: date
        comments_path: "#__comments"
extra:
  consent:
    title: Cookie consent
    description: >- 
      We use cookies to recognize your repeated visits and preferences, as well
      as to measure the effectiveness of our documentation and whether users
      find what they're searching for. With your consent, you're helping us to
      make our documentation better.
    homepage: https://niaodtiantang.github.io/

repo_url: https://github.com/niaodtiantang/niaodtiantang.github.io/
repo_name: niaodtiantang/niaodtiantang.github.io
edit_uri: https://github.com/niaodtiantang/niaodtiantang.github.io/edit/main/docs/

markdown_extensions:
    - pymdownx.highlight:
        anchor_linenums: true
    - pymdownx.inlinehilite
    - pymdownx.snippets
    - pymdownx.superfences
    - tables
    - footnotes
    - pymdownx.critic
    - pymdownx.caret
    - pymdownx.keys
    - pymdownx.mark
    - pymdownx.tilde
    - attr_list
    - md_in_html
    - admonition
    - pymdownx.details
    - pymdownx.superfences
    - attr_list
    - pymdownx.emoji:
        emoji_index: !!python/name:materialx.emoji.twemoji
        emoji_generator: !!python/name:materialx.emoji.to_svg
